about/urls.py
from django.urls import path

import about.views

app_name = "about"

urlpatterns = [
    path("", about.views.AboutView.as_view(), name="about"),
]

erai_clean/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path("about/", include("about.urls")),
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("feedback/", include("feedback.urls")),
    path("gallery/", include("gallery.urls")),
    path("", include("homepage.urls")),
    path("order/", include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path

import homepage.views
import gallery

app_name = "homepage"

urlpatterns = [
    path(
        "",
        homepage.views.HomeView.as_view(),
        name="home",
    ),
    path(
        "add-review/",
        homepage.views.AddReviewView.as_view(),
        name="add_review",
    ),
    path(
        "",
        gallery.views.GalleryView.as_view(),
        name="gallery"
    ),
]

order/urls.py
from django.urls import path
from order import views


app_name = "order"
urlpatterns = [
    path("", views.OrderView.as_view(), name="order_create"),
    path("ajax/calculate/", views.ajax_calculate_price, name="ajax_calculate"),
]

templates/includes/header.html
{% load static %}
<div class="header">
  <div class="logo">
    <a href="/"><img src="/static/static_media/erai-logo-for-footer.png" alt="Logo"></a>
  </div>
  <nav class="nav-links">
    	<a href="{% url 'homepage:home' %}">Main Page</a>
		{% if request.resolver_match.view_name != 'about:about' %}
    	<a href="{% url 'about:about' %}">About Team</a>
		{% endif %}
		{% if request.resolver_match.view_name != 'order:order' %}
    	<a href="{% url 'order:order_create' %}">Book Now</a>
		{% endif %}
		{% if request.resolver_match.view_name != 'catalog:catalog' %}
    	<a href="{% url 'catalog:catalog' %}">Cleaning Services</a>
		{% endif %}
		{% if request.resolver_match.view_name != 'feedback:feedback' %}
    	<a href="{% url 'feedback:feedback' %}">Reach Erai</a>
		{% endif %}
  </nav>
</div>
<script src="{% static 'js/header.js' %}"></script>