about/urls.py
from django.urls import path

import about.views

app_name = "about"

urlpatterns = [
    path("", about.views.AboutView.as_view(), name="about"),
]

erai_clean/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path("about/", include("about.urls")),
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("feedback/", include("feedback.urls")),
    path("gallery/", include("gallery.urls")),
    path("", include("homepage.urls")),
    path("order/", include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path

import homepage.views
import gallery

app_name = "homepage"

urlpatterns = [
    path(
        "",
        homepage.views.HomeView.as_view(),
        name="home",
    ),
    path(
        "add-review/",
        homepage.views.AddReviewView.as_view(),
        name="add_review",
    ),
    path(
        "",
        gallery.views.GalleryView.as_view(),
        name="gallery"
    ),
]

reviews/models.py
from django.db import models


class Review(models.Model):

    work_description = models.CharField(max_length=100)

    text = models.TextField()

    is_visible_on_main = models.BooleanField(default=False)

    name = models.CharField(max_length=100)

    link = models.CharField(blank=True, max_length=200)

    source_name = models.CharField(blank=True, max_length=100)

    source = models.ImageField(
        verbose_name="source image",
        help_text="upload an image of source",
        upload_to="images/review_sources/",
        blank=True,
    )

    class Meta:
        verbose_name = "review"
        verbose_name_plural = "reviews"

    def __str__(self):
        return f"Отзыв от {self.name}: {self.work_description}"

reviews/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["work_description", "text", "name"]
        widgets = {
            "work_description": forms.TextInput(
                attrs={
                    "class": "input",
                    "placeholder": "Describe our work in one word",
                }
            ),
            "text": forms.Textarea(
                attrs={
                    "class": "input",
                    "placeholder": "Your review",
                }
            ),
            "name": forms.TextInput(
                attrs={
                    "class": "input",
                    "placeholder": "Your name",
                }
            ),
        }
        labels = {
            "work_description": "Work Description",
            "text": "Review Text",
            "name": "Name",
        }

templates/reviews/reviews.html
{% load static %}

<div id="reviews" class="reviews-section">
  <h1 class="reviews-title">Live Reviews</h1>

  <div class="reviews-background-cropper">
    <div class="reviews-background"></div>
  </div>
  <div class="reviews-wrapper">
    <div class="reviews-container">
      <div style="width: 10px;"></div>

      {% for review in reviews %}
        <a href="{{ review.link }}" class="review-card" {% if not review.link %}onclick="return false;"{% endif %} target="_blank">
          <div class="review-header">
            <div class="review-name">{{ review.name }}</div>
            {% if review.source %}
              <div class="review-logo">
                <img src="{{ review.source.url }}" alt="User photo">
              </div>
            {% endif %}
          </div>
          {% if review.work_description %}
            <p class="review-title">{{ review.work_description }}</p>
          {% endif %}
          <div class="review-text-box">{{ review.text }}</div>
        </a>
      {% empty %}
        <p class="text-center">Here is no reviews yet</p>
      {% endfor %}

      <div style="width: 10px;"></div>
    </div>
  </div>

  <button class="add-review-btn" onclick="openModal()">Leave a Review</button>
</div>

<div id="reviewModal" class="modal">
  <div style="height: 25%;"></div>
  <div class="modal-content">
    <span class="close" onclick="closeModal()">&times;</span>
    <div style="height: 25px;"></div>
    <h2>Leave a Review</h2>
    <div style="height: 25px;"></div>
    <form method="POST" action="{% url 'homepage:add_review' %}">
      {% csrf_token %}
      <div class="form-group">
        <input class="modal-input" type="text" id="name" name="name" maxlength="100" required>
        <label for="name">Your name</label>
      </div>
      <div class="form-group">
        <input class="modal-input" type="text" id="work_description" name="work_description" maxlength="100" required>
        <label for="work_description">Our work in one word</label>
      </div>
      <div class="form-group">
        <textarea class="modal-textarea" id="text" name="text" rows="4" required></textarea>
        <label for="text">Review</label>
      </div>
      <button type="submit" class="submit-btn">Submit</button>
    </form>
  </div>
</div>

<script src="{% static 'js/modal.js' %}"></script>
<script src="{% static 'js/reviews.js' %}"></script>