about/urls.py
from django.urls import path

import about.views

app_name = "about"

urlpatterns = [
    path("", about.views.AboutView.as_view(), name="about"),
]

erai_clean/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path("about/", include("about.urls")),
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("feedback/", include("feedback.urls")),
    path("gallery/", include("gallery.urls")),
    path("", include("homepage.urls")),
    path("order/", include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path

import feedback.views

app_name = "feedback"

urlpatterns = [
    path("", feedback.views.FeedbackView.as_view(), name="feedback"),
]

feedback/models.py
from django.db import models


class Feedback(models.Model):

    subject = models.CharField(
        verbose_name="subject",
        help_text="enter your subject",
        max_length=50,
    )

    text = models.TextField(
        verbose_name="text",
        help_text="enter your text",
    )

    class Meta:
        verbose_name = "feedback"
        verbose_name_plural = "feedbacks"

feedback/forms.py
from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField(max_length=20)
    subject = forms.CharField(max_length=150)
    message = forms.CharField(widget=forms.Textarea)

feedback/views.py
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy
from feedback.forms import FeedbackForm
from feedback.models import Feedback
from catalog import models


class FeedbackView(FormView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = models.Service.objects.filter(service_is_published=True)
        return context

    template_name = "feedback/feedback.html"
    form_class = FeedbackForm
    success_url = reverse_lazy("feedback:feedback")

    def form_valid(self, form):
        print("FORM VALID: sending email...")
        data = form.cleaned_data
        subject = f"New contact: {data['subject']}"
        message = (
            f"Name: {data['name']}\n"
            f"Email: {data['email']}\n"
            f"Phone: {data['phone']}\n\n"
            f"Message:\n{data['message']}"
        )

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            ["aimansclub@gmail.com"],
            fail_silently=False,
        )

        Feedback.objects.create(
            subject=data["subject"],
            text=message,
        )

        return super().form_valid(form)


class FeedbackHomeView(FormView):
    template_name = "feedback/feedback_home.html"
    form_class = FeedbackForm
    success_url = reverse_lazy("homepage:home")

    def form_valid(self, form):
        print("FORM VALID: sending email...")
        data = form.cleaned_data
        subject = f"New contact: {data['subject']}"
        message = (
            f"Name: {data['name']}\n"
            f"Email: {data['email']}\n"
            f"Phone: {data['phone']}\n\n"
            f"Message:\n{data['message']}"
        )

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            ["aimansclub@gmail.com"],
            fail_silently=False,
        )

        Feedback.objects.create(
            subject=data["subject"],
            text=message,
        )

        return super().form_valid(form)

templates/feedback/feedback.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="erai-banner-wrapper">
  <img src="{% static 'static_media/contact_head.webp' %}" alt="Background" class="erai-banner-img">
  <div class="erai-banner">
    <h1>Contact Us</h1>
  </div>
</section>
{% include "feedback/feedback_home.html" %}


{% endblock %}

templates/feedback/feedback_home.html
<section class="feedback-section">
  <div class="feedback-left">
    <div class="feedback-glass">
      <h1>Contact us</h1>
      <div class="feedback-info-box">
        <p>Every review matters — just as much as the smallest detail.</p>
        <p>That’s why we always welcome your voice. Whether it’s a question, a concern, or simply a thought to share, we are here to listen, to respond, and to guide you. For us, feedback isn’t just a formality — it’s the foundation that helps us grow and serve you better every day.</p>
      </div>
    </div>
  </div>
  
  <div class="feedback-right">
    <form method="post" action="{% url 'feedback:feedback' %}" class="feedback-form">
      {% csrf_token %}
      <div class="feedback-form-row">
        <div class="feedback-form-group">
          <input type="text" name="name" placeholder=" " id="id_name">
          <label for="id_name">Name</label>
        </div>
        <div class="feedback-form-group">
          <input type="text" name="phone" placeholder=" " id="id_phone">
          <label for="id_phone">Phone</label>
        </div>
      </div>
      
      <div class="feedback-form-row">
        <div class="feedback-form-group">
          <input type="email" name="email" placeholder=" " id="id_email">
          <label for="id_email">Email</label>
        </div>
        <div class="feedback-form-group">
          <input type="text" name="subject" placeholder=" " id="id_subject">
          <label for="id_subject">Subject</label>
        </div>
      </div>
      
      <div class="feedback-form-group feedback-full-width">
        <textarea name="message" placeholder=" " id="id_message"></textarea>
        <label for="id_message">Message</label>
      </div>
      
      <button type="submit" class="feedback-submit-btn">Send</button>
    </form>
  </div>
</section>